#Application Configuration
server:
  port: 8092

security:
  basic:
    enable: false
  ignored: /**

# To See H2 Console in Browser:
# http://localhost:8091/h2-console
# Enabling H2 Console
spring:
  application:
    name: cron-service
  h2:
    console:
      enabled: true
    # ===============================
    # DB
    # ===============================
    # url: jdbc:h2:mem:productDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    # url: jdbc:sqlserver://localhost;database=prueba;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    # url: jdbc:sqlserver://localhost;database=PALATSI_43VO01;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    # password: S3rv3r.123
    # driverClassName: org.h2.Driver
  datasource:
    url: jdbc:sqlserver://${DB_URL};DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
   # hibernate:
   #   ddl-auto: update
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
  sql:
    init:
      platform: mssql
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
my:
  url:
    palatsi:  ${PALATSI_URL}
    palatsi_prod_new:  ${PALATSI_PROD_NEW}
    dolphin:  ${DOLPHIN_URL}
    ellence:  ${ELLENCE_URL}
    prueba:  ${PALATSI_URL}
    pass_palatsi:  ${PALATSI_PASS}
    pass_dolphin:  ${DOLPHIN_PASS}
    pass_ellence:  ${ELLENCE_PASS}
    pass_prueba:  ${PALATSI_PASS}

